INSERT INTO public.categorie (img,nome,slug) VALUES
	 ('icon-snack.svg','snack','snack'),
	 ('icon-drink.svg','bevande','bevande'),
	 ('icon-instant-meal.svg','cibo istantaneo','cibo-istantaneo'),
	 ('icon-sauce.svg','salse','salse'),
	 ('icon-fresh.svg','prodotti freschi','prodotti-freschi');
INSERT INTO public.contatti ("name",email,message) VALUES
	 ('gab','gab@gmail.com','gab ha inviato una mail'),
	 ('gggg','ggg@hhh.it','nnnv');
INSERT INTO public.prodotti (img,titolo,codice,descbreve,stelle,recensioni,prezzo,qta,descrizione,tabnutrizione,ingredienti,categoria,prezzo_visibile) VALUES
	 ('makgeolli-chestnut.webp','Makgeolli Sapore Castagna 750ml','mc750','Gusta la Corea con il Makgeolli al sapore castagna. Non potrai più farne a meno.',4,7,5.99,3,'Bevanda alcolica di origine coreana che ti farà sentire immerso nella vita quotidiana di Itaweon. Gusta la Corea con con gli altri sapori disponibili.','','Riso, Lievito, Nuruk (Koji), Acqua, Acido Alimentare (E330), Regolatore di Acidità (E270 latte), Dolcificante Artificiale (E951).','bevande','si'),
	 ('torta-kasutera-latte-castella.webp','Torta Kasutera Latte (Castella)','tokacas','Monoporzione di torta soft al latte . Castella (カステラ kasutera). Non potrai più farne a meno, il sapore inconfondibile del Giappone, più precisamente della città di Nagasaki.',5,18,1.29,6,'Sapore di latte dell’Hokkaido. La torta Castella giapponese è un popolare pan di spagna giapponese così soffice e umido. La torta Castella fu originariamente introdotta in Giappone dai mercanti portoghesi che entrarono nell’area di Nagasaki nel XVI secolo e il suo nome deriva dal portoghese Pão de Castella, o “pane di Castiglia”. Questa torta castella pronta da mangiare viene pre-affettata ed è un modo perfetto per aggiornare il tuo menu di dessert!','','UOVA 5%, farina di FRUMENTO, olio di palma, acqua, sciroppo di glucosio, latte in polvere, sale, emulsionanti (E492, E422, E475, E435, E471, E450i, E477, E322), addensante (E415), regolatori di acidità (E500ii, E575), colorante (E170), conservante, aromi','snack','si'),
	 ('salsa-teriyaki-kikkoman.webp','Salsa Teriyaki Densa Kikkoman 250ml','sauterkik','La salsa Teriyaki di Kikkoman è composta da salsa di soia ricca di aromi, aceto e zucchero moscovado che conferiscono al tuo piatto un sapore dolce, caldo e leggermente aspro.',5,12,3.5,5,'ll teriyaki è un piatto nazionale giapponese che può essere tradotto come “grigliato” e “splendente”. Ingredienti come pesce, carne o verdure vengono prima marinati e poi grigliati o brasati. La salsa Teriyaki di Kikkoman è composta da salsa di soia ricca di aromi, aceto e zucchero moscovado che conferiscono al tuo piatto un sapore dolce, caldo e leggermente aspro. Usa la salsa Amoy Teriyaki per marinare il cibo e per ricoprirlo dopo la cottura alla griglia.','','Salsa di soia (acqua, semi di soia , frumento , sale), zucchero, acqua, semi di sesamo (1,6%), amido modificato, aceto di spirito, aglio in polvere, pepe nero, sale, estratto di peperoncino','salse','si'),
	 ('kimchi-tagliato-bibigo.webp','Kimchi Coreano Fresco & Verdure Tagliato Bibigo 150Gr','bibikim150','Il kimchi è un piatto tradizionale coreano a base di verdure fermentate ed è un alimento base della cucina coreana.

Bigigo è il marchio di kimchi numero 1 in Corea!',5,32,3.99,5,'Il kimchi è un piatto tradizionale coreano a base di verdure fermentate ed è un alimento base della cucina coreana.

Bigigo è il marchio di kimchi numero 1 in Corea!

Questo kimchi di cavolo tagliato, viene prodotto condendo e fermentando il cavolo tritato con una miscela piccante e piccante di scaglie di peperoncino, aglio, zenzero e altri condimenti. È un contorno saporito e salutare che può essere gustato da solo o utilizzato come condimento in vari piatti coreani.

- Utilizza polvere di peperoncino rosso di alta qualità per catturare il delizioso colore del kimchi.
- Il sale solare naturale al 100% dona una consistenza croccante.
','','Cavolo Napa, Ravanello, Peperone Rosso, Aglio, Zucchero, Cipolla, Cipolla Verde, Porro, Carota, Estratto Di Glutine Di Grano, Zenzero, Sale','prodotti-freschi','si'),
	 ('buldak-kimchi.webp','Ramyun Coreano Buldak Paprika & Kimchi','rambulpap','I Samyang Hot Ramen Noodles sono uno dei tipi di noodles più popolari nel sud-est asiatico e sono leader di mercato per il cibo coreano.',5,23,1.99,0,'Noti per essere uno dei ramyeon più piccanti disponibili sul mercato coreano. I fiocchi sono fatti di alghe secche e semi di sesamo. Deliziosi noodle piccanti con semi di sesamo e fiocchi di alghe grigliate.','','Noodle (74,3%): farina di frumento , amido di tapioca modificato, olio di palma raffinato, glutine di frumento , sale raffinato, emulsionante [ lecitina di soia (E322)], correttore di acidità [carbonato di potassio (E501(I)), carbonato di sodio (E500(I) )), fosfato di sodio bibasico (E339(Ii)), acido citrico (E330)], addensante [gomma di guar (E412)], olio aromatizzato al tè verde. Zuppa (23,7%): acqua, zucchero bianco, polvere di kimchi, aroma artificiale di pollo, sciroppo di mais, olio di semi di soia , pasta di peperoni rossi, potere di peperoncino, SALSA DI soia , cipolla, polvere artificiale di aroma di pollo, esaltatore di sapidità [L-glutammato monosodico (E621)], polvere di peperone rosso, aglio, fecola di patate modificata, estratto di paprika, estratto di peperoncino decolorato, colorante [polvere di caramello (E150c)], polvere di pepe nero , Correttore di acidità [acido EL-malico (E296)] Fiocchi (2,0%): Fiocchi di Kimchi essiccati. Contiene: grano , glutine , allergeni di soia : per gli allergeni, vedere gli ingredienti in grassetto. Prodotto in uno stabilimento che lavora anche sedano, cereali contenenti glutine, crostacei, uova, pesce, latte, molluschi, senape, frutta a guscio, arachidi, semi di sesamo e prodotti a base di soia.','cibo-istantaneo','si'),
	 ('icon-mystery.svg','Prodotto Misterioso 👀','pm','Un prodotto Misterioso ti aspetta, tenta la fortuna...',5,12,0.0,10,'Tenta la fortuna con il prodotto misterioso che riceverai con la tua Lucky Box.','','👀👀👀','','no'),
	 ('alga-nori.webp','Snack Alga Nori Coreana & Olio di Mais & Sesamo','snakan','Fogli sottili e croccanti di alga nori tostata. Assapra la Corea con questi snack dal gusto inconfondibile.',4,12,0.99,3,'Fogli sottili e croccanti di alga nori tostata . Il sapore inconfondibile dell’alga nori si unisce a una consistenza croccante e leggera. Il sapore dell’alga nori è uno dei prodotti marini con più proprietà per il nostro organismo.

Questo snack, una creazione più recente, viene servito in deliziosi bocconcini perfetti per uno spuntino informale. Il Gim coreano è conosciuto in tutto il mondo per il suo ambiente di produzione pulito e la tecnologia superiore, e le sue tecniche di aromatizzazione svolgono un ruolo significativo nella sua popolarità. Il Gim coreano è completato dal sapore ricco dell’olio di sesamo e del sale di alta qualità proveniente dalle coste coreane, che esaltano appieno la naturale freschezza e fragranza delle alghe. Si tratta infatti di uno spuntino o di un contorno ambito da tutti, la cui qualità può addirittura superare quella della Cina o del Giappone.','','alghe (porphyra tenera), olio di mais, olio di oliva, olio di sesamo, sale, tè verde in polvere.','snack','si'),
	 ('bibigo-gyoza-beef-bulgogi-600g.webp','Gyoza Coreani Manzo in Salsa Bulgogi','gymabul','Gyoza coreani con bulgogi di manzo:
In questa variante coreana, il ripieno è a base di bulgogi, una marinatura a base di salsa di soia, zucchero, aglio, cipolla e altri aromi, che rende la carne di manzo tenera e saporita.',4,5,15.99,4,'Gyoza coreani con bulgogi di manzo:
In questa variante coreana, il ripieno è a base di bulgogi, una marinatura a base di salsa di soia, zucchero, aglio, cipolla e altri aromi, che rende la carne di manzo tenera e saporita.
- Caratteristiche:
Involucro: Sottile e leggermente traslucido, spesso con bordi ondulati o zigrinati.

Ripieno: A base di bulgogi di manzo, un mix di carne marinata, verdure tritate (come carote e cipolle) e spezie.

Gusto: Un mix di sapori intenso e avvolgente, con la dolcezza della marinata bulgogi che si sposa perfettamente con la sapidità della carne e la delicatezza dell’involucro.

Cottura: Possono essere cotti al vapore, fritti o arrostiti, conferendo loro diverse texture. Se fritti, avranno una crosta dorata e croccante, mentre se cotti al vapore saranno più morbidi e delicati.

- Come si servono:

Salsa: Spesso vengono serviti con salsa di soia, salsa piccante coreana (gochujang) e aceto di riso, che bilanciano i sapori e aggiungono un tocco di piccantezza.

Contorni: Si sposano bene con riso bianco, zuppe, noodles o verdure saltate','',' Verdure 32% [Cipolla, Cipolla, Cavolo cappuccio, Carota, Aglio, Manzo 24%, Farina di frumento , Acqua, Salsa di mele [Mela, Sciroppo di glucosio-fruttosio, Zucchero, Correttore di acidità [Acido citrico], Antiossidante [Acido ascorbico]] , salsa di soia [acqua, semi di soia , frumento , sale], zucchero, amido di tapioca, olio di sesamo , amido di mais, estratto di lievito, proteine ​​isolate di soia , sale, glutine di frumento , sciroppo di zucchero, spezie, olio di colza. Può contenere tracce di Latte, Uova, Senape, Crostacei .','prodotti-freschi','si'),
	 ('shiki-tofu.webp','Tofu Giapponese “Prima Classe” Shiki & Soft (300Gr)','togishso','l tofu Satono Yuki è quanto di più simile si possa ottenere al tofu fresco e setoso in una confezione a lunga conservazione.',5,21,3.5,6,'l tofu Satono Yuki è quanto di più simile si possa ottenere al tofu fresco e setoso in una confezione a lunga conservazione. Con oltre il 25% di contenuto di soia, il tofu contiene quasi il doppio della soia di altre marche di tofu, per renderlo più nutriente e conferire un sapore più ricco. Il tofu giapponese premium è un ottimo ingrediente da dispensa. Servire a cubetti nelle zuppe di miso, ricoprire con fecola di patate prima di friggere per preparare il tofu agedashi, oppure scaldare in acqua calda e servire con zenzero finemente grattugiato, cipollotto affettato e salsa di soia come semplice antipasto.

Adatto per la zuppa di miso*

ll tofu è un fantastico alimento salutare in Giappone che viene prodotto coagulando il latte di soia fino a quando non diventa abbastanza sodo da essere pressato in blocchi a basso contenuto di grassi, ma ricchi di proteine. Il tofu “di seta” è diverso dal normale tofu per la sua consistenza morbida e la sua natura versatile che lo rende adatto sia a piatti salati che a dessert.','',' Acqua, fagioli di soia, agente rassodante E511','prodotti-freschi','si'),
	 ('kit-bubble-tea-latte-crema-taro.webp','Kit Bubble Tea Latte & Crema di Taro (3 Porzioni)','kitbubtealata3','Per i curiosi e gli appassionati di Boba, invece, c’è questo kit intelligente, che non è necessario che provenga da un apposito negozio Bubble Tea in città.',5,7,7.99,7,'Per i curiosi e gli appassionati di Boba, invece, c’è questo kit intelligente, che non è necessario che provenga da un apposito negozio Bubble Tea in città.

Le perle di tapioca sono qui abbinate al delizioso frutto della radice di taro, che si riconosce per il suo delicato colore viola e il sapore unico con note di noci e vaniglia.

Set Composto da:

- 3 Bubble tea istantanei (50g)
- 3 Confezioni di latte in polvere (35 g)','','Polvere di "tè al latte": zucchero, "panna in polvere" non casearia (sciroppo di glucosio, olio di palma idrogenato, amido modificato (E1450), stabilizzante (E340ii), emulsionante (E471), addensante (E551)), aroma artificiale di taro, polvere di taro 2%, anti- agente agglomerante (E551), emulsionante (E466), polvere di barbabietola rossa, polvere di patata dolce viola. Perle di tapioca istantanee: acqua, amido di tapioca, fruttosio, addensanti (E1422, E1442, E1413), aroma di zucchero di canna, stabilizzante (E415), emulsionanti (E422, E440, E466), colorante (E150d), correttore di acidità (E296).','bevande','si');
